var arrlang = {
  'en': {
    'how': 'How to play',
    'credit': 'Credits',
    'game': 'Game',
    'contribute': 'Contributors',
    'character': 'Characters',
    'statistics': 'Statistics',
    'moved': 'Player Moved :',
    'times': ' Times',
    'spent': 'Time spent :',
    'audio': 'Audio',
    'now': 'Now Playing : ',
    'by': ' by ',
    'share': ' Share Game ',
    'follow': 'Follow us on',
    'invent': 'Inventory',
    'badge': 'Your Badges',
    'version': 'Version',
    'license': 'License',
    'start': "Let's start",
    'how1': "You'll see the base room with doors on it's walls. Notice the red and grey tile, there are 4 doors/openings on 4 walls.",
    'how2': "Press the upward arrow button for go to room above the current room (precisely, top left corner of your screen or north-west direction taking north towards the top of your screen)",
    'how3': "Now you can see a new block/room added. Also see that the color difference of the tiles. The bring red shows the current (red) active tile and the dark (black) tile shows the rest of tiles. Let's move a bit towards right now",
    'code': 'press right arrow',
    'how4': "We can see the tiles to the right (top-right precisely). We can see the doors towards all sides/walls of the room/block. So let's move more in the game.", 
    'how5': "We can see that there's no tile towards the top, so now we cannot move more in that direction. Let's go about making a complete grid. Do you see a way now too ? There is still an open door to explore!",
    'done': 'All done!',
    'finish': "Now it's your turn to explore, you can also contribute & create your own tiles.",
    'rate': 'Rate game',
    'rate-question': 'How do you enjoy the game so far?',
    
    /*------------------
    full sentence of following strings from 'made-by' to 'licensed' is like following,
    Icon made by Gregor Cresnar from www.flaticon.com is licensed by CC 3.0 BY
    ------------------*/
    /*------------*/
    'made-by': 'Icon made by ',
    'from': 'from',
    'licensed-by': ' is licensed by ',
    'licensed': 'CC 3.0 BY',
    /*------------*/

    'play': 'Play',
    'icon': 'Icons by ',
    'flaticon': 'flaticon.com',

  },
  'si': {
    'how': 'ක්‍රීඩා කරන්නේ කෙසේ ද',
    'credit': 'සම්මානය',
    'game': 'ක්‍රීඩාව',
    'contribute': 'දායකයින්',
    'character': 'චරිත',
    'statistics': 'සංඛ්‍යාමය දත්ත',
    'moved': 'ඇදීම වාර :',
    'times': '  යි',
    'spent': 'ගතකල කාලය : ',
    'audio': 'නාද',
    'now': 'දැන් වාදනය වන්නේ : ',
    'by': ' ලබා දුන්නේ, ',
    'share': ' ක්‍රීඩාව ගැන හුවමාරු කරන්න ',
    'follow': 'අපව අනුගමනය කරන්න',
    'invent': 'අතැති ද්‍රව්‍ය',
    'badge': 'ඔබගේ පදක්කම්',
    'version': 'සංස්කරණය',
    'license': 'බලපත්‍රය',
    'start': "අපි පටන් ගමු",
    'how1': "ඔබට එහි බිත්ති සමග දොරවල් ඇති ප්‍රධාන කාමරයක් දැකිය හැකි ය. රතු සහ අළු බිමක් ඇති, බිත්ති 4ක් සමඟ දොරවල්/පිටවුම් 4ක් ඇත.",
    'how2': "වත්මන් කාමරයට ඉහලින් ඇති කාමරයට යාමට ඉහළ ඊතල බොත්තම ඔබන්න (හරියටම ඔබේ තිරයේ ඉහළ වම් කෙළවරේ හෝ ඊසාන දිශාව උතුරු දෙසට ගෙන ඔබගේ තිරයේ මුදුනට ගමන් කරන්න)",
    'how3': "දැන් ඔබට තවත් බ්ලොක්/කාමරයක් දැකිය හැකිය. ටයිල්වල වර්ණ වෙනසත් දකින්න. රතු පැහැයෙන් වත්මන් (රතු) ක්‍රියාකාරී බිම දැක්වෙන අතර අනෙක් බිම් අඳුරු (කළු) බිම් ලෙස දක්නට ලැබේ. දැන් අපි තව ටිකක් ඉදිරියට යමු",
    'code': 'දකුණු ඊතලය හරින්න',
    'how4': "ඉහළට දෙසට තවත් ටයිල් එකක් නොමැති බව අපට දැක ගත හැකි ය, එනිසා දැන් අපට එම දිශාව තුළ තවදුරටත් ගමන් කළ නොහැකිය. පූර්ණ ජාලයක් සෑදීමට අපි යමු. දැන් ඔබට මාර්ගයක් දකින්නට පුළුවන්ද? ගවේෂණයට විවෘත දොරක් තවමත් තිබේ!",
    'how5': "අපිට දකුණට (වයඹ දිසාවට) ඇති බිම් දැකිය හැකි ය. අපිට කාමර/බ්ලොක්වල හැම පැත්තකට ම/බිත්තියක් දෙසට ම ඇති දොරවල් දකින්න පුළුවන්. ඉතින් අපි ක්‍රීඩාව තුළ වැඩි වැඩියෙන් ඇවිදිමු.",
    'done': 'ඔක්කොම හරි!',
    'finish': "දැන් එය ගවේෂණය කිරීම සඳහා ඔබේ අවස්ථාව, ඔබට ඔබේම බිම් සැදීමට ද දායක විය හැකිය.",
    'rate': 'ක්‍රීඩාවට කැමැත්ත ප්‍රකාශ කරන්න',
    'rate-question': 'ක්‍රීඩාවෙන් ඔබ කොතරම් දුරට සතුටු වූයේ ද?',
    'made-by': '',
    'from': 'මඟින්',
    'flaticon.com': 'www.flaticon.com ට',
    'licensed-by': ' සැකසූ අයිකන',
    'licensed': 'CC 3.0 BY යටතේ බලපත්‍ර ගත කොට ඇත.',
    'play': 'ක්‍රීඩා කරන්න.',
    'icon': 'අයිකන ',
    'flaticon': 'flaticon.com මඟිනි',
  },
    'hi': {
      'how': 'कैसे खेलें',
      'credit': 'आभार',
      'game': 'खेल',
      'contribute': 'योगदानकर्ता',
      'character': 'वर्ण',
      'statistics': 'आंकड़े',
      'moved': 'खिलाड़ी चला :',
      'times': ' अवसर',
      'spent': 'समय बिताया : ',
      'audio': 'ऑडियो',
      'now': 'अभी खेल रहे है : ',
      'by': ' द्वारा ',
      'share': ' Share Game ',
      'follow': 'हमारा अनुसरण इस पर कीजिये',
      'invent': 'सुचि',
      'badge': 'आपके बैज',
      'version': 'संस्करण',
      'license': 'अनुज्ञप्ति',
      'start': "चलो शुरू करें",
      'how1': "आप आधार कक्ष को दीवारों पर दरवाजे के साथ देखेंगे। लाल और ग्रे टाइल की सूचना दें, 4 दीवारों पर 4 द्वार / उद्घाटन हैं।",
      'how2': "वर्तमान कमरे से ऊपर के कमरे में जाने के लिए ऊपरी तीर बटन दबाएं (ठीक है, आपकी स्क्रीन के शीर्ष बाएं कोने या उत्तर-पश्चिम की दिशा में आपकी स्क्रीन के ऊपर की ओर उत्तर)",
      'how3': "अब आप एक नया ब्लॉक / कमरा जोड़ सकते हैं। यह भी देखें कि टाइल का रंग अंतर लाल लाओ वर्तमान (लाल) सक्रिय टाइल दिखाता है और अंधेरे (काला) टाइल शेष टाइल दिखाता है। आइए अभी थोड़ा सा कदम आगे बढ़ें",
      'code': 'दायां तीर दबाएं',
      'how4': "हम दायीं ओर टाइल देख सकते हैं (ठीक-ठीक सही)। हम कमरे / ब्लॉक की सभी तरफ / दीवारों के लिए दरवाजे देख सकते हैं। तो चलो खेल में और अधिक स्थानांतरित", 
      'how5': "हम देख सकते हैं कि शीर्ष पर कोई टाइल नहीं है, इसलिए अब हम उस दिशा में अधिक नहीं जा सकते। एक पूर्ण ग्रिड बनाने के बारे में चलें। क्या आप अभी भी एक रास्ता देखते हैं? अभी भी तलाशने का एक खुला दरवाजा है!",
      'done': 'सभी कार्य पूर्ण!',
      'finish': "अब यह पता लगाने की आपकी बारी है, आप अपनी टाईल्स को भी योगदान और बना सकते हैं।",
      'rate': 'खेल का मूल्यांकन करें',
      'rate-question': 'आप इस खेल का आनंद कैसे करते हैं?',
      
      /*------------------
      full sentence of following strings from 'made-by' to 'licensed' is like following,
      Icon made by Gregor Cresnar from www.flaticon.com is licensed by CC 3.0 BY
      ------------------*/
      /*------------*/
      'made-by': 'Icon made by ',
      'from': 'से',
      'licensed-by': ' द्वारा लाइसेंस प्राप्त है ',
      'licensed': 'CC 3.0 BY',
      /*------------*/
  
      'play': 'खेलना',
      'icon': 'द्वारा आइकन ',
      'flaticon': 'flaticon.com',
  
    },
  'pl': {
      'how': 'Jak grać?',
      'credit': 'CREDITS',
      'game': 'Gra',
      'contribute': 'Twórcy',
      'character': 'Postacie',
      'statistics': 'Statystyki',
      'moved': 'Liczba ruchów :',
      'times': ' razy',
      'spent': ' :',
      'audio': 'Audio',
      'now': 'Teraz leci : ',
      'by': ' by ',
      'share': ' Udostępnij ',
      'follow': 'Śledź nas',
      'invent': 'Wyposarzenie',
      'badge': 'Twoje Odznaki',
      'version': 'Wersja',
      'license': 'Licencja',
      'start': "Zacznijmy",
      'how1': "Zobaczysz podstawowy pokój z drzwiami w ścianach. Zauważ czerwone i szare pola, są 4 drzwi/przejścia w 4 ścianach.",
      'how2': "Wciśnij strzałkę w górę aby przejść do pokoju znadującego się wyrzej (dokładnie, lewy górny róg Twojego ekranu lub północno-zachodni kierunek jeśli Twój ekran zwrócony jest w stronę północy)",
      'how3': "Odkryjesz nowy pokój. Zauważ również, że zmienił się kolor pola. Kolor pokazuje obecne, aktywne pole zaś reszta pól jest znacznie przyciemniona. Pójdźmy teraz w prawo",
      'code': 'wciśnij strzałkę w prawo',
      'how4': "Możemy zobaczyć pola do prawej strony (dokładnie, górnej prawej strony). Widzimy drzwi ze wszystkich stron pokoi. Idźmy dalej.", 
      'how5': "Widzimy, że na górze nie ma już drzwi, wieć nie możemy iść w tym kierunku. Stwórzmy kompletną siatkę. Czy Ty już też widzisz drogę? Wciąż są otwarte drzwi do odkrycia!",
      'done': 'Udało się!',
      'finish': "Teraz Twoja kolej, możesz się również przyczynić do projektu i dodać własne pola.",
      'play': 'Zagraj',
      'icon': 'Icons by ',
      'flaticon': 'flaticon.com',
    }
};

$(function () {
  $('.translate').click(function () {
    var lang = $(this).attr('id');

    $('.lang').each(function (index, element) {
      $(this).text(arrlang[lang][$(this).attr('data-href')]);
    });
  });
});
